---
- hosts: all
  become: yes
  roles:
    - common
    - role: systemd
      vars:
        systemd_mDNS:
          - interface: enp0s8
            state: true
  tasks:
    - name: ssh config for vagrant hosts
      become: true
      ansible.builtin.template:
        dest: /etc/ssh/ssh_config.d/vagrant.conf
        group: root
        mode: 0644
        owner: root
        src: "templates/ssh/ssh_config.j2"
        trim_blocks: false
        
- hosts: k8s-0
  become: yes
  roles:
    - role: ansible
      tags: ["ansible"]
    - role: globus-personal
      tags: ["globus-personal"]
    - role: k8s-admin
      tags: ["k8s-admin"]

- hosts: microk8s
  become: yes
  roles:
    - role: microk8s
      tags: ["microk8s"]
      vars:
        microk8s_group_members:
          - vagrant
        microk8s_ipv4address: "{{ ansible_enp0s8.ipv4.address }}"

#- hosts: docker-swarm-*
#  roles:
#    - role: dockerSwarm
#      tags: []
#      vars: {}
