---
- hosts: all
  become: yes
  roles:
    - common
    - role: systemd
      vars:
        systemd_mDNS:
          - interface: enp0s8
            state: true

- hosts: k8s-0
  become: yes
  roles:
    - role: ansible
      tags: ["ansible"]
    - role: k8s-admin
      tags: ["k8s-admin"]
    - role: docker
      tags: ["docker"]
      vars:
        docker_group_members:
          - vagrant
    - role: k8s-dev
      tags: ["k8s-dev"]

- hosts: microk8s
  become: yes
  roles:
    - role: microk8s
      tags: ["microk8s"]
      vars:
        microk8s_group_members:
          - vagrant
        microk8s_ipv4address: "{{ ansible_enp0s8.ipv4.address }}"

- hosts: docker_swarm
  become: yes
  roles:
    - role: docker
      tags: ["docker-swarm"]
      vars:
        docker_group_members:
          - vagrant
