---
# ansible-galaxy collection install -r requirements.yml
# ansible-galaxy role install -r requirements.yml
collections:
  - community.general
  - community.kubernetes
  #- kubernetes.core

roles:
  - name: ansible
    src: https://github.com/dean-taylor/ansible-role-ansible
    version: main
  - name: common
    src: https://github.com/dean-taylor/ansible-role-common
    version: main
  - name: docker
    src: https://github.com/dean-taylor/ansible-role-docker
    version: main
  - name: k8s-admin
    src: https://github.com/dean-taylor/ansible-role-k8s-admin
    version: main
  - name: k8s-dev
    src: https://github.com/dean-taylor/ansible-role-k8s-dev.git
    version: main
  - name: microk8s
    src: https://github.com/dean-taylor/ansible-role-microk8s
    version: main
  - name: systemd
    src: https://github.com/dean-taylor/ansible-role-systemd
    version: main
