---
# ansible-galaxy collection install -r requirements.yml
# ansible-galaxy role install -r requirements.yml
collections:
  - community.general
  - community.kubernetes
  #- kubernetes.core

roles:
  - name: docker
    src: https://github.com/dean-taylor/ansible-role-docker
    version: main
  - name: systemd
    src: https://github.com/dean-taylor/ansible-role-systemd
    version: main
